/*
 * File: app/store/DeliveryType.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.store.DeliveryType', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'DeliveryType',
            data: [
                {
                    delivery_name: 'Top Priority',
                    delivery_type: 'top'
                },
                {
                    delivery_name: 'Priority',
                    delivery_type: 'priority'
                },
                {
                    delivery_name: 'Standard',
                    delivery_type: 'standard'
                }
            ],
            fields: [
                {
                    name: 'delivery_type'
                },
                {
                    name: 'delivery_name'
                }
            ]
        }, cfg)]);
    }
});