/*
 * File: app/store/FutureYearOfDelivery.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.store.FutureYearOfDelivery', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'FutureYearOfDelivery',
            data: [
                {
                    code: '01',
                    year: '2017'
                },
                {
                    code: '02',
                    year: '2018'
                },
                {
                    code: '03',
                    year: '2019'
                },
                {
                    code: '04',
                    year: '2020'
                },
                {
                    code: '05',
                    year: '2021'
                },
                {
                    code: '06',
                    year: '2022'
                },
                {
                    code: '07',
                    year: '2023'
                },
                {
                    code: '08',
                    year: '2024'
                },
                {
                    code: '09',
                    year: '2025'
                },
                {
                    code: '10',
                    year: '2026'
                },
                {
                    code: '11',
                    year: '2027'
                },
                {
                    code: '12',
                    year: '2028'
                }
            ],
            fields: [
                {
                    name: 'code'
                },
                {
                    name: 'year'
                }
            ]
        }, cfg)]);
    }
});