/*
 * File: app/store/FutureMonthOfDelivery.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.store.FutureMonthOfDelivery', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'FutureMonthOfDelivery',
            data: [
                {
                    code: '01',
                    month: 'January'
                },
                {
                    code: '02',
                    month: 'February'
                },
                {
                    code: '03',
                    month: 'March'
                },
                {
                    code: '04',
                    month: 'April'
                },
                {
                    code: '05',
                    month: 'May'
                },
                {
                    code: '06',
                    month: 'June'
                },
                {
                    code: '07',
                    month: 'July'
                },
                {
                    code: '08',
                    month: 'August'
                },
                {
                    code: '09',
                    month: 'September'
                },
                {
                    code: '10',
                    month: 'October'
                },
                {
                    code: '11',
                    month: 'November'
                },
                {
                    code: '12',
                    month: 'December'
                }
            ],
            fields: [
                {
                    name: 'code'
                },
                {
                    name: 'month'
                }
            ]
        }, cfg)]);
    }
});