/*
 * File: app/store/FuturePaymentTypes.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.store.FuturePaymentTypes', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'FuturePaymentTypes',
            data: [
                {
                    rate: 0.9,
                    name: 'Staggered after 90% down payment'
                },
                {
                    rate: 0.8,
                    name: 'Staggered after 80% down payment'
                },
                {
                    rate: 0.75,
                    name: 'Staggered after 75% down payment'
                },
                {
                    rate: 0.6,
                    name: 'Staggered after 60% down payment'
                },
                {
                    rate: 0.5,
                    name: 'Staggered after 50% down payment'
                },
                {
                    rate: 0.4,
                    name: 'Staggered after 40% down payment'
                },
                {
                    rate: 0.3,
                    name: 'Staggered after 30% down payment'
                },
                {
                    rate: 0.25,
                    name: 'Staggered after 25% down payment'
                },
                {
                    rate: 0.20,
                    name: 'Staggered after 20% down payment'
                },
                {
                    rate: 0.15,
                    name: 'Staggered after 15% down payment'
                },
                {
                    rate: 0.1,
                    name: 'Staggered after 10% down payment'
                },
                {
                    rate: 0.05,
                    name: 'Staggered after 5% down payment'
                }
            ],
            fields: [
                {
                    name: 'rate'
                },
                {
                    name: 'name'
                }
            ]
        }, cfg)]);
    }
});