/*
 * File: app/store/RequesterType.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.store.RequesterType', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'RequesterType',
            data: [
                {
                    type: 'Investor',
                    info: 'Investors'
                },
                {
                    type: 'Merchant',
                    info: 'Merchant'
                },
                {
                    type: 'Corporate_institution',
                    info: 'Corporate Institution'
                },
                {
                    type: 'Public_institution',
                    info: 'Public Institution'
                },
                {
                    type: 'Individual',
                    info: 'Individual'
                }
            ],
            fields: [
                {
                    name: 'type'
                },
                {
                    name: 'info'
                }
            ]
        }, cfg)]);
    }
});