/*
 * File: app/store/SubscriptionDayOfDelivery.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.store.SubscriptionDayOfDelivery', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'SubscriptionDayOfDelivery',
            data: [
                {
                    day_of_delivery: 'Monday'
                },
                {
                    day_of_delivery: 'Tuesday'
                },
                {
                    day_of_delivery: 'Wednesday'
                },
                {
                    day_of_delivery: 'Thursday'
                },
                {
                    day_of_delivery: 'Friday'
                },
                {
                    day_of_delivery: 'Saturday'
                },
                {
                    day_of_delivery: 'Sunday'
                },
                {
                    day_of_delivery: 'Any_day'
                }
            ],
            fields: [
                {
                    name: 'day_of_delivery'
                }
            ]
        }, cfg)]);
    }
});