/*
 * File: app/store/TimeOfContact.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.store.TimeOfContact', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'TimeOfContact',
            data: [
                {
                    contact_time: 'Before_12noon'
                },
                {
                    contact_time: 'Between_12noon_and_3pm'
                },
                {
                    contact_time: 'Between_3pm_and_7pm'
                },
                {
                    contact_time: 'Between_7pm_and_9pm'
                }
            ],
            fields: [
                {
                    name: 'contact_time'
                }
            ]
        }, cfg)]);
    }
});